version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.voila
    expose:
      - 8866

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
